name: Deploy SQL Server Database

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install SQLCMD
        run: sudo apt-get install mssql-tools unixodbc-dev

      - name: Execute SQL Scripts
        run: |
          sqlcmd -S ${{ secrets.DB_SERVER }} -U ${{ secrets.DB_USERNAME }} -P ${{ secrets.DB_PASSWORD }} -d YourDatabase -i scripts/create_tables.sql
